// <auto-generated />
using System;
using CompetitionsTracking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompetitionsTracking.Infrastructure.Migrations
{
    [DbContext(typeof(CompetitionsTrackingDbContext))]
    partial class CompetitionsTrackingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Apparatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("apparatus");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Appeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("appeals");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinAge")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("competitions");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApparatusId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApparatusId");

                    b.ToTable("disciplines");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<string>("EntryStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("entries");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Judge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("QualificationLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("judges");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("participants", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardedMedal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<float>("FinalScore")
                        .HasColumnType("real");

                    b.Property<int>("Place")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntryId")
                        .IsUnique();

                    b.ToTable("results");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<int>("JudgeId")
                        .HasColumnType("int");

                    b.Property<float>("ScoreValue")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("JudgeId");

                    b.ToTable("scores");
                });

            modelBuilder.Entity("team_members", b =>
                {
                    b.Property<int>("team_id")
                        .HasColumnType("int");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.HasKey("team_id", "person_id");

                    b.HasIndex("person_id");

                    b.ToTable("team_members");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Person", b =>
                {
                    b.HasBaseType("CompetitionsTracking.Domain.Entities.Participant");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("MentorId");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Team", b =>
                {
                    b.HasBaseType("CompetitionsTracking.Domain.Entities.Participant");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CoachId");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Appeal", b =>
                {
                    b.HasOne("CompetitionsTracking.Domain.Entities.Result", "Result")
                        .WithMany("Appeals")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Discipline", b =>
                {
                    b.HasOne("CompetitionsTracking.Domain.Entities.Apparatus", "Apparatus")
                        .WithMany("Disciplines")
                        .HasForeignKey("ApparatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apparatus");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Entry", b =>
                {
                    b.HasOne("CompetitionsTracking.Domain.Entities.Category", "Category")
                        .WithMany("Entries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompetitionsTracking.Domain.Entities.Competition", "Competition")
                        .WithMany("Entries")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompetitionsTracking.Domain.Entities.Discipline", "Discipline")
                        .WithMany("Entries")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompetitionsTracking.Domain.Entities.Participant", "Participant")
                        .WithMany("Entries")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Competition");

                    b.Navigation("Discipline");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Judge", b =>
                {
                    b.HasOne("CompetitionsTracking.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Result", b =>
                {
                    b.HasOne("CompetitionsTracking.Domain.Entities.Entry", "Entry")
                        .WithOne("Result")
                        .HasForeignKey("CompetitionsTracking.Domain.Entities.Result", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Score", b =>
                {
                    b.HasOne("CompetitionsTracking.Domain.Entities.Entry", "Entry")
                        .WithMany("Scores")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompetitionsTracking.Domain.Entities.Judge", "Judge")
                        .WithMany("Scores")
                        .HasForeignKey("JudgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Judge");
                });

            modelBuilder.Entity("team_members", b =>
                {
                    b.HasOne("CompetitionsTracking.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompetitionsTracking.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("team_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Person", b =>
                {
                    b.HasOne("CompetitionsTracking.Domain.Entities.Participant", null)
                        .WithOne()
                        .HasForeignKey("CompetitionsTracking.Domain.Entities.Person", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompetitionsTracking.Domain.Entities.Person", "Mentor")
                        .WithMany("Mentees")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Team", b =>
                {
                    b.HasOne("CompetitionsTracking.Domain.Entities.Person", "Coach")
                        .WithMany("TeamsCoached")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompetitionsTracking.Domain.Entities.Participant", null)
                        .WithOne()
                        .HasForeignKey("CompetitionsTracking.Domain.Entities.Team", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Apparatus", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Category", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Competition", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Discipline", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Entry", b =>
                {
                    b.Navigation("Result")
                        .IsRequired();

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Judge", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Participant", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Result", b =>
                {
                    b.Navigation("Appeals");
                });

            modelBuilder.Entity("CompetitionsTracking.Domain.Entities.Person", b =>
                {
                    b.Navigation("Mentees");

                    b.Navigation("TeamsCoached");
                });
#pragma warning restore 612, 618
        }
    }
}
